sudo: required

language: cpp

install:
- git clone https://github.com/raspberrypi/tools.git --depth=1
- export PATH=$(pwd)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH
- pushd opdi_core/code/c/libraries/POCO
- ./build_poco_rpi.sh
- ./build_poco.sh
- popd

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

script: 
- export CXX=g++-4.9
- export CC=gcc-4.9
- make -C src/openhatd/openhatd/ CC=$CC
- export PATH=$(pwd)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH
- make -C src/openhatd/openhatd/ -f makefile-rpicc
