sudo: required

arch: i686

language: cpp

install:
- git clone https://github.com/raspberrypi/tools.git --depth=1
- export PATH=$(pwd)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH
- cp -r opdi_core/code/c/libraries/POCO_patches/* opdi_core/code/c/libraries/POCO/
- pushd opdi_core/code/c/libraries/POCO
#- ./build_poco_rpi.sh
- ./build_poco_i386.sh
- ./build_poco.sh
- popd
- sudo pip install mkdocs

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-multilib
    - gcc-4.9
    - g++-4.9
    - gcc-4.9-multilib
    - g++-4.9-multilib
    - linux-libc-dev:i386
    - lib32stdc++6
    - sshpass
    - python-pip

script: 
- export SSHPASS=$RELEASE_UPLOAD_PASSWORD 
- mkdocs build
- tar czf OpenHAT-docs.tar.gz OpenHAT-docs/
- md5sum OpenHAT-docs.tar.gz > OpenHAT-docs.tar.gz.md5
- sshpass -e scp -P $RELEASE_UPLOAD_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no OpenHAT-docs.tar.gz* $RELEASE_UPLOAD_USER@$RELEASE_UPLOAD_HOST:~/.documentation
- export CXX=g++-4.9
- export CC=g++-4.9
- export PATH=$(pwd)/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH
#- make -C src/openhatd/openhatd/ -f makefile-rpicc
- make -C src/openhatd/openhatd/ -f makefile-i386 CC=$CC
- make -C src/openhatd/openhatd/ CC=$CC
- make -C src/openhatd/openhatd/ tests && sshpass -e scp -P $RELEASE_UPLOAD_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /home/travis/build/openhat-org/OpenHAT/src/openhatd/openhatd/*.tar.gz* $RELEASE_UPLOAD_USER@$RELEASE_UPLOAD_HOST:~

notifications:
  email:
    recipients:
      - maintainer@openhat.org
