sudo: required

language: cpp

install:
- pushd opdi_core/code/c/libraries/POCO
- ./build_poco.sh
- ./build_poco_rpi.sh
- popd

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - binutils-arm-linux-gnueabi
    - gcc-arm-linux-gnueabihf
    - g++-arm-linux-gnueabihf

script: 
- export CXX=g++-4.
- export CC=gcc-4.9
- make -C src/openhatd/openhatd/
- make -C src/openhatd/openhatd/ -f makefile-rpi
