

clone_depth: 1

install:
  - ps: (new-object System.Net.WebClient).DownloadFile('https://the.earth.li/~sgtatham/putty/latest/x86/pscp.exe', 'pscp.exe')
  - pscp -v -P %RELEASE_UPLOAD_PORT% -batch -l %RELEASE_UPLOAD_USER% -pw %RELEASE_UPLOAD_PASSWORD% -hostkey %RELEASE_UPLOAD_HOSTKEY% *.exe %RELEASE_UPLOAD_HOST%:~
  - git submodule update --init --recursive
  - copy opdi_core\code\c\libraries\POCO_patches\* opdi_core\code\c\libraries\POCO\
  - cd opdi_core\code\c\libraries\POCO\
  - buildwin 140 build static_mt release Win32 nosamples notests
  - cd %APPVEYOR_BUILD_FOLDER%
  - pip install mkdocs
  - set /p "OPENHATD_VERSION=" < src\openhatd\openhatd\VERSION

configuration: Release

build:
  project: src\openhatd\openhatd.sln

after_build:
  - cd src\openhatd\openhatd
  - release.bat
  - $(APPVEYOR_BUILD_FOLDER)\pscp -v -P %RELEASE_UPLOAD_PORT% -batch -l %RELEASE_UPLOAD_USER% -pw %RELEASE_UPLOAD_PASSWORD% -hostkey %RELEASE_UPLOAD_HOSTKEY% openhatd*.zip %RELEASE_UPLOAD_HOST%:~

notifications:
  - provider: Email
    to:
      - maintainer@openhat.org
    on_build_status_changed: true
