

clone_depth: 1

install:
  - scp
  - git submodule update --init --recursive
  - copy opdi_core\code\c\libraries\POCO_patches\* opdi_core\code\c\libraries\POCO\
  - cd opdi_core\code\c\libraries\POCO\
  - buildwin 140 build static_mt release Win32 nosamples notests
  - cd %APPVEYOR_BUILD_FOLDER%
  - pip install mkdocs
  - set /p "OPENHATD_VERSION=" < src\openhatd\openhatd\VERSION

configuration: Release

build:
  project: src\openhatd\openhatd.sln

after_build:
  - cd src\openhatd\openhatd
  - release.bat
  - echo open %FTP_UPLOAD_HOST%>upload.ftp
  - echo %FTP_UPLOAD_USER%>>upload.ftp
  - echo %FTP_UPLOAD_PASSWORD%>>upload.ftp
  - echo quote pasv>>upload.ftp
  - echo mput *.zip>>upload.ftp
  - echo quit>>upload.ftp
  - ftp -i -s:upload.ftp

notifications:
  - provider: Email
    to:
      - maintainer@openhat.org
    on_build_status_changed: true
