install:
  - copy c:\projects\openhat\opdi_core\code\c\libraries\POCO_patches\* c:\projects\openhat\opdi_core\code\c\libraries\POCO\
  - c:\projects\openhat\opdi_core\code\c\libraries\POCO\buildwin 140 build all both Win32 nosamples notests
  - pip install mkdocs

platform:
  - x86
  
configuration:
  - Release
  
matrix:
  fast_finish: true

build:
  project: src\openhatd\openhatd.sln
  
notifications:
  - provider: Email
    to:
      - maintainer@openhat.org
