install:
  - git submodule update --init --recursive
  - copy opdi_core\code\c\libraries\POCO_patches\* opdi_core\code\c\libraries\POCO\
  - cd opdi_core\code\c\libraries\POCO\
  - buildwin 140 build all both Win32 nosamples notests
  - pip install mkdocs

build:
  project: src\openhatd\openhatd.sln
  
notifications:
  - provider: Email
    to:
      - maintainer@openhat.org
