

clone_depth: 1

install:
  - ps: (new-object System.Net.WebClient).DownloadFile('https://the.earth.li/~sgtatham/putty/latest/x86/pscp.exe', 'pscp.exe')
  - choco install doxygen.install -y
  - git submodule update --init --recursive
  - copy opdi_core\code\c\libraries\POCO_patches\* opdi_core\code\c\libraries\POCO\
  - cd opdi_core\code\c\libraries\POCO\
  - buildwin 140 build static_mt release Win32 nosamples notests
  - cd %APPVEYOR_BUILD_FOLDER%
  - pip install mkdocs
  - pip install markdown-include
  - set /p "OPENHATD_VERSION=" < openhatd\src\VERSION

configuration: Release

build:
  project: openhatd\openhatd.sln

test_script:
  - cd openhatd\src
  - openhatd.exe -c hello-world.ini -t -q
  - openhatd.exe -c ..\testconfigs\dev.ini -t -q
  - openhatd.exe -c ..\testconfigs\weather_test.ini -t -q
  - openhatd.exe -c ..\testconfigs\window_test.ini -t -q
  - openhatd.exe -c ..\testconfigs\testconfig.ini -t -q
  - cd %APPVEYOR_BUILD_FOLDER%

after_test:
  - cd openhatd\src
  - release.bat
  - pscp -v -P %RELEASE_UPLOAD_PORT% -batch -l %RELEASE_UPLOAD_USER% -pw %RELEASE_UPLOAD_PASSWORD% -hostkey %RELEASE_UPLOAD_HOSTKEY% openhatd*.zip* %RELEASE_UPLOAD_HOST%:.
  - cd %APPVEYOR_BUILD_FOLDER%

notifications:
  - provider: Email
    to:
      - maintainer@openhat.org
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
