site_name: OpenHAT - The Open Home Automation Toolkit
strict: true
use_directory_urls: false
site_url: https://openhat.org
site_description: OpenHAT Open Home Automation Toolkit documentation
site_dir: OpenHAT-docs
theme: readthedocs
pages:
    - Introduction to OpenHAT: index.md
extra_css:
    - extra.css
copyright: <p style="font-size:small">Copyright <a href="http://openhat.org">OpenHAT</a> contributors. Found something unclear, wrong or missing? Please <a href="https://github.com/openhat-org/OpenHAT/issues/new?title=OpenHAT%20Documentation%3A%20">open an issue</a>!</p>
