# openhatd makefile
# Creates a release file that includes plugins.
# Pass DEBUG=1 to enable a debug build.

MAKEFILE = $(firstword $(MAKEFILE_LIST))

# build specific settings

CFLAGS = -fPIC -shared -static-libstdc++

include common.mk


