# openhatd makefile
# Creates a release file that includes plugins.
# Pass DEBUG=1 to enable a debug build.

MAKEFILE = $(firstword $(MAKEFILE_LIST))

# build specific settings

DEBUG = 1

# The compiler to be used.
CC = g++

# Compiler flags.
CFLAGS = -static-libstdc++

include common.mk


