site_name: openhatd <br>Open Home Automation Toolkit Server
theme: readthedocs
pages:
    - Introduction to openhatd: index.md
    - Download and installation: download.md
    - Documentation:
        - Basic Concepts: concepts.md
        - Configuration Details: configuration.md
        - Advanced Ports: ports.md
        - Details: details.md
        - Ports:
            - Logic Port: ports/logic_port.md
            - Pulse Port: ports/pulse_port.md
            - Selector Port: ports/selector_port.md
            - Error Detector Port: ports/error_detector_port.md
            - Logger Port: ports/logger_port.md
            - Fader Port: ports/fader_port.md
            - Scene Select Port: ports/scene_select_port.md
            - File Port: ports/file_port.md
            - Aggregator Port: ports/aggregator_port.md
            - Counter Port: ports/counter_port.md
            - Trigger Port: ports/trigger_port.md
            - InfluxDB Port: ports/influxdb_port.md
        - Plugins:
            - General:
                - Web Server Plugin: plugins/webserver_plugin.md 
            - Automation:
                - FRITZ!Box Plugin: plugins/automation/fritzbox_plugin.md
                - Weather Plugin: plugins/automation/weather_plugin.md
                - Window Plugin: plugins/automation/window_plugin.md
            - Raspberry Pi:
                - Gertboard Plugin: plugins/rpi/gertboard/gertboard_plugin.md
                - RemoteSwitch Plugin: plugins/rpi/remoteswitch_plugin.md
    - Feedback: feedback.md
extra_css:
    - extra.css
