site_name: openhatd __VERSION__<br>Open Home Automation Toolkit Server
strict: true
site_url: https://openhat.org/openhatd
site_description: openhatd home automation server documentation
site_dir: openhatd-docs-__VERSION__
theme: readthedocs
pages:
    - Introduction to openhatd: index.md
    - Download and installation: download.md
    - Documentation:
        - Basic Concepts: concepts.md
        - Port Overview: ports.md
        - Configuration: configuration.md
        - Automation Examples: automation_examples.md
        - Details: details.md
        - Ports:
            - Basic Ports: ports/basic_ports.md
            - Logic Port: ports/logic_port.md
            - Pulse Port: ports/pulse_port.md
            - Selector Port: ports/selector_port.md
            - Error Detector Port: ports/error_detector_port.md
            - Logger Port: ports/logger_port.md
            - Fader Port: ports/fader_port.md
            - Scene Select Port: ports/scene_select_port.md
            - File Port: ports/file_port.md
            - Aggregator Port: ports/aggregator_port.md
            - Counter Port: ports/counter_port.md
            - Trigger Port: ports/trigger_port.md
            - InfluxDB Port: ports/influxdb_port.md
        - Plugins:
            - General:
                - Web Server Plugin: plugins/webserver_plugin.md 
            - Automation:
                - FRITZ!Box Plugin: plugins/automation/fritzbox_plugin.md
                - Weather Plugin: plugins/automation/weather_plugin.md
                - Window Plugin: plugins/automation/window_plugin.md
            - Raspberry Pi:
                - Gertboard Plugin: plugins/rpi/gertboard/gertboard_plugin.md
                - RemoteSwitch Plugin: plugins/rpi/remoteswitch_plugin.md
        - Deploying openhatd: deployment.md
    - Feedback: feedback.md
    - Contributing: contributing.md
    - Development: development.md
extra_css:
    - extra.css
copyright: <p style="font-size:small">openhatd __VERSION__ Built: __TIMESTAMP__ Copyright <a href="http://openhat.org">OpenHAT</a> contributors. Found something unclear, wrong or missing? Please <a href="https://github.com/openhat-org/OpenHAT/issues/new?title=openhatd%20Documentation%3A%20">open an issue</a>!</p>
