site_name: openhatd 0.2.0<br>Open Home Automation Toolkit Server
strict: false
use_directory_urls: false
site_url: https://openhat.org/openhatd
site_description: openhatd home automation server documentation
site_dir: openhatd-docs-0.2.0
theme: readthedocs
markdown_extensions:
    - markdown_include.include
pages:
    - Introduction to openhatd: index.md
    - Download and installation: download.md
    - Documentation:
        - Basic Concepts: concepts.md
        - Port Overview: ports.md
        - Configuration: configuration.md
        - Automation Examples: automation_examples.md
        - Ports:
            - Basic Ports: ports/basic_ports.md
            - Aggregator Port: ports/aggregator_port.md
            - Assignment Port: ports/assignment_port.md
            - Counter Port: ports/counter_port.md
            - ErrorDetector Port: ports/error_detector_port.md
            - Exec Port: ports/exec_port.md
            - Expression Port: ports/expression_port.md
            - Fader Port: ports/fader_port.md
            - File Port: ports/file_port.md
            - InfluxDB Port: ports/influxdb_port.md
            - Logger Port: ports/logger_port.md
            - Logic Port: ports/logic_port.md
            - Pulse Port: ports/pulse_port.md
            - Scene Select Port: ports/scene_select_port.md
            - Selector Port: ports/selector_port.md
            - Test Port: ports/test_port.md
            - Timer Port: ports/timer_port.md
            - Trigger Port: ports/trigger_port.md
        - Plugins:
            - General:
                - Web Server Plugin: plugins/webserver_plugin.md 
            - Automation:
                - FRITZ!Box Plugin: plugins/automation/fritzbox_plugin.md
                - Weather Plugin: plugins/automation/weather_plugin.md
                - Window Plugin: plugins/automation/window_plugin.md
            - Raspberry Pi:
                - Gertboard Plugin: plugins/rpi/gertboard/gertboard_plugin.md
                - RemoteSwitch Plugin: plugins/rpi/remoteswitch_plugin.md
        - Appliances:
            - Xiaomi Mi Robot Vacuum Cleaner: appliances/xiaomi_mi_robovac.md
        - Deploying openhatd: deployment.md
    - Feedback: feedback.md
    - Contributing: contributing.md
    - Development: development.md
    - Doxygen documentation: doxygen/index.md
    - Release Notes: release_notes.md
    - Release Plan: release_plan.md
extra_css:
    - extra.css
extra_javascript: []
copyright: <p style="font-size:small">openhatd documentation<br>Copyright <a href="http://openhat.org">OpenHAT</a> contributors. Found something unclear, wrong or missing? Please <a href="https://github.com/openhat-org/OpenHAT/issues/new?title=openhatd%20Documentation%3A%20">open an issue</a>!</p>
